### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by marawan6569** [LinuxDevil/site-analyzer#1]
### While testing the speed-analyzer.py , I came across an error.

![image](https://user-images.githubusercontent.com/38116633/229933230-0c88e6f1-462c-4f96-b764-f9df139148f4.png)

 ### I noticed that the node-app folder was missing, 
and instead found a folder named js. To solve the issue, I renamed the js folder to node-app. However, this change led to another error, which is shown in the second image."
![image](https://user-images.githubusercontent.com/38116633/229933306-2f311f9b-c34d-4b35-9bab-2abb8b651c6c.png)

**Comment by marawan6569** [comment]
## You should also update README.md with new file name ``` speed-analyzer.py ```
![image](https://user-images.githubusercontent.com/38116633/229934535-23769e12-1b26-48b1-b831-5a06994d0603.png)

**Comment by LinuxDevil** [comment]
Thank you so much for submitting the issue! 

It should be solved with #2
